defaults:
  - hard
  - _self_

task_name: humanoid_walk
lr: 8e-5
feature_dim: 100

suite: dmc
hydra:
  job:
    env_set:
      # Environment variables for MuJoCo
      MKL_SERVICE_FORCE_INTEL: '1'
      MUJOCO_GL: 'egl'