defaults:
  - _self_
  - task@_global_: dmc/quadruped_walk
  - override hydra/launcher: submitit_local

# Environment
suite: DMC
frame_stack: 3
action_repeat: 2
obs_spec: ???  # To be specified later
# Agent
lr: 1e-4
feature_dim: 50
# Replay
nstep: 3
batch_size: 256
discount: 0.99
# Training
seed_steps: 4000
# Evaluating
evaluate_per_steps: 10000
evaluate_episodes: 10
# Saving
save_session: false
# Logging
log_video: true
log_tensorboard: true
# Misc
device: cuda
# Experiment
seed: 1
experiment: experiment_name

environment:
  _target_: Datasets.Environments.Environment.Environment
  task_name: ${task_name}
  frame_stack: ${frame_stack}
  action_repeat: ${action_repeat}
  max_episode_frames: false
  truncate_episode_frames: 1000
  seed: ${seed}
  suite: ${suite}

agent:
  _target_: Agents.DQNDPGAgent
  obs_shape: ${obs_spec}
  action_shape: ??? # To be specified later
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  target_tau: 0.01
  stddev_schedule: ${stddev_schedule} # Specified in task/easy,medium,hard
  stddev_clip: 0.3
  explore_steps: 2000
  lr: ${lr}
  update_per_steps: 2
  discrete: ??? # To be specified later
  device: ${device}
  log_tensorboard: ${log_tensorboard}

replay:
  _target_: Datasets.Experiences.ExperienceReplay.ExperienceReplay
  storage_dir: ???  # To be specified later
  obs_spec: ???  # To be specified later
  action_spec: ???  # To be specified later
  capacity: 1000000
  batch_size: ${batch_size}}
  num_workers: 4
  nstep: ${nstep}
  discount: ${discount}
  save: false

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
  # Environment variables for MuJoCo
  job:
    env_set:
      MKL_SERVICE_FORCE_INTEL: '1'
      MUJOCO_GL: 'egl'
