defaults:
  - _self_
  - task@_global_: dmc/quadruped_walk
  - override hydra/launcher: submitit_local

# environment
suite: DMC
frame_stack: 3
action_repeat: 2
# agent
lr: 1e-4
feature_dim: 50
# replay
nstep: 3
batch_size: 256
discount: 0.99
# training
seed_steps: 4000
# evaluating
evaluate_per_steps: 10000
evaluate_episodes: 10
# saving
save_session: false
# logging
log_video: true
log_tensorboard: true
# misc
device: cuda
# experiment
seed: 1
experiment: experiment_name

environment:
  _target_: Datasets.Environments.Environment.Environment
  task_name: ${task_name}
  frame_stack: ${frame_stack}
  action_repeat: ${action_repeat}
  max_episode_frames: false
  truncate_episode_frames: 1000
  seed: ${seed}
  suite: ${suite}

agent:
  _target_: Agents.DQNDPGAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  feature_dim: ${feature_dim}
  hidden_dim: 1024
  target_tau: 0.01
  stddev_schedule: ${stddev_schedule} # specified in task/easy,medium,hard
  stddev_clip: 0.3
  explore_per_steps: 2000
  lr: ${lr}
  update_per_steps: 2
  discrete: ??? # to be specified later
  device: ${device}
  log_tensorboard: ${log_tensorboard}

replay:
  _target_: Datasets.Experiences.ExperienceReplay.ExperienceReplay
  capacity: 1000000
  batch_size: ${batch_size}}
  num_workers: 4
  nstep: ${nstep}
  discount: ${discount}
  save: false

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
  job:
    env_set: MUJOCO_GL
    env_copy: MKL_SERVICE_FORCE_INTEL
